<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
?>
<h3><?= $escaper->escapeHtml(__('Would you like to individualize the DHL parcel announcement?')) ?></h3>
<p><?= /* @noEscape */ __('You can now display your logo and the desired store name in the parcel notification. Use the following <a href="https://www.dhl.de/de/geschaeftskunden/paket/versandsoftware/dhl-paketankuendigung/formular.html" target="_blank">form</a> to do so.') ?></p>
