<div class="col col-l-7 col-xl-8 content">
    <p>Nam quis condimentum velit, ut sodales lorem. Vivamus sit amet odio a leo lobortis mattis. Aliquam
        tempus augue sed ante elementum, vitae pharetra orci tincidunt. Praesent et est sit amet ligula
        tristique vehicula in eu arcu.</p>
    <p>Proin molestie ligula eu tellus tristique, sed convallis sapien feugiat. Praesent gravida non mauris vitae
        pharetra. Vestibulum ante ipsum primis in faucibus.</p>
</div>
<div class="col col-l-5 col-xl-4">
    <aside style="padding: 1em; background: white; border: 1px solid #e3e3e3">
        <p>Having issues configuring the extension? Contact your DHL account
            representative who will facilitate technical assistance.</p>
    </aside>
</div>
