<?php
/**
 * See LICENSE.md for license details.
 */
?>
<div class="col col-l-7 col-xl-8 content">
    <p>
        DHL Paket provides parcel shipping across Germany and to more than 220 countries - even on Saturdays.
    </p>
    <p>
        Furthermore, the DHL Paket carrier allows to request shipping labels for incoming orders directly within
        your Magento instance.
    </p>
    <p>To get started:</p>
    <ol>
        <li>
            You must have a valid DHL Paket business account<br/>
            <small>If you don’t have an account or your account is with another DHL division,
                <a href="https://www.dhl.de/en/geschaeftskunden/paket/kunde-werden/angebot-dhl-geschaeftskunden-online.html" target="_blank">please contact DHL Paket</a> to establish or expand your
                relationship
            </small>
        </li>
        <li>
            Your DHL Paket business account must be configured for API access<br/>
            <small>If you didn’t discuss this with your account representative when you set up your account, please
                consult them to enable your API access</small>
        </li>
    </ol>
</div>
<div class="col col-l-5 col-xl-4">
    <aside style="padding: 1em; background: white; border: 1px solid #e3e3e3">
        <h3>DHL & Magento</h3>
        <p>Having issues configuring the extension? Contact your DHL Paket account
            representative who will facilitate technical assistance.</p>
    </aside>
</div>
