<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Dhl\Paket\ViewModel\Adminhtml\System\Config\InfoBox $viewModel */
$viewModel = $block->getData('view_model');
?>
<div class="col content">
    <p>
        <?= $block->escapeHtml(__('DHL Paket provides parcel shipping across Germany and to more than 220 countries. ')) ?>
    </p>
    <p>
        <?= $block->escapeHtml(__('Furthermore, the DHL Paket module allows to request shipping labels for incoming orders directly within your Magento suite.')) ?>
    </p>
    <p><?= $block->escapeHtml(__('To get started:')) ?></p>
    <ol>
        <li>
            <?= $block->escapeHtml(__('You need to have a valid DHL Paket business account number (EKP)')) ?>
            <br/>
            <em>
                <small>
                    <?= /* @noEscape */ __('If you do not have a DHL Paket account, <a href="https://www.dhl.de/en/geschaeftskunden/paket/kunde-werden/angebot-dhl-geschaeftskunden-online.html" target="_blank">please contact DHL Paket</a> to establish or expand your relationship') ?>
                </small>
            </em>
        </li>
        <li>
            <?= $block->escapeHtml(__('In addition to your account number you need your 2-digit Procedure and Participation number')) ?>

        </li>
    </ol>
</div>
<div class="col side">
    <aside>
        <div class="section">
            <h3><?= $block->escapeHtml(__('Post & DHL and Magento')) ?></h3>
            <p>
                <?= $block->escapeHtml(__('Having issues configuring the extension? Contact our support desk:')) ?>
                <a href="mailto:<?= $block->escapeHtml(__('dhl.support@netresearch.de'))?>">
                    <?= $block->escapeHtml(__('dhl.support@netresearch.de'))?>
                </a>
            </p>
        </div>
        <?= $block->getBlockHtml('dhlshipping_paket_infobox_additional') ?>
    </aside>
</div>
