<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Dhl\Paket\ViewModel\Adminhtml\System\Config\InfoBox\PostDirektAdditional $viewModel */
$viewModel = $block->getData('view_model');
?>
<div class="section">
    <h3><?= $block->escapeHtml('DHL Shipping') ?></h3>
    <p>
        <?= $block->escapeHtml(__('Create shipping labels & tracking information for your orders directly in the Magento admin panel.')) ?>
        <?= $block->escapeHtml(
                __(
                    '%1DHL Parcel Germany%2 is an ideal complement to the AUTOCOMPLETE and ADDRESSFACTORY services of Deutsche Post Direkt.',
                    '<a href="' . $block->escapeUrl($viewModel->getConfigGroupLink()) . '">',
                    '</a>'
                ),
                ['a']
            )
        ?>
    </p>
</div>
